require('dotenv').config();

const fs = require('fs');
const path = require('path');

const generatedEnvPath = path.join(__dirname, 'config', 'env.generated.ts');
const envContent = `// Auto-generated by metro.config.js — do not edit manually
export const TMDB = ${JSON.stringify(process.env.TMDB ?? '')};
export const BaseUrl = ${JSON.stringify(process.env.BaseUrl ?? '')};
export const ImageUrl = ${JSON.stringify(process.env.ImageUrl ?? '')};
`;
fs.writeFileSync(generatedEnvPath, envContent, 'utf8');

const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('@react-native/metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
